### ISSUE TITLE
Plugin errors for iPhone

### ISSUE THREAD

**Issue by kinsbrunner** [pupunzi/jquery.mb.YTPlayer#262]
Hi,
I am working on a website which uses your plugin to reproduce a video and works perfectly fine when using it on Chrome, Edge or IE from my laptop but, unfortunately, it is triggering some errors when trying to open it on iPhone or, from Safari (on my laptop) or, Chrome (with dev tools immitating iPhone6).

These are the errors I am getting:
![bugs](https://cloud.githubusercontent.com/assets/16242832/26366220/934e9ac2-3fc0-11e7-93e2-f66659eb2b26.png)

You can see the implementation on www.expinconsulting.com

The file jquery.mb.YTPlayer.src.js was last modified on 24/10/16 22.30.

Kindly let me know in case you have a workaround for this.

Thanks and regards.

Alejandro.

**Comment by pupunzi** [comment]
@kinsbrunner 
This issue should be fixed with the latest 3.0.19 release.
Did you try updating the plug-in?

Let me know,
Matteo

**Comment by kinsbrunner** [comment]
@pupunzi 
Matteo, 
I have moved into version 3.0.19 and first issue still there BUT second issue changes...

![bugs_2](https://cloud.githubusercontent.com/assets/16242832/26368711/cdd4b87c-3fc8-11e7-8a6e-e5d3f9c8ac23.png)

Thanks for everything.
Alejandro.

**Comment by pupunzi** [comment]
Hi,
You're including the jquery.mb.YTPlayer.src.js but you've to include the javascript files in the "dist" folder instead: 
jquery.mb.YTPlayer.js od jquery.mb.YTPlayer.min.js
and the CSS file in the same "dist" folder.

The src folder is not compiled.

**Comment by kinsbrunner** [comment]
Matteo,
I have paster the content of the 4 minified js which were on the Dist folder into the end of the js file I have uploaded... I though that would be enough. Kindly confirm.
Otherwise, is there a way of only adding 1 unique file?
Regards.
Alejandro.

**Comment by pupunzi** [comment]
The error is from a minified JS file (http://www.expinconsulting.com/assets/application-cedc947e8692df016bb27e64712148d018de972c793bdff2d266d0a2ee6c14f8.js) where the YTPlayer javascript minified inclusion is wrong (is the jquery.mb.YTPlayer.src.js file). You should include the jquery.mb.YTPlayer.min.js file instead.

**Comment by kinsbrunner** [comment]
Sorry, just forgot to push into Production. Still an issue...

**Comment by pupunzi** [comment]
It's hard to debug your minified script... 
The error comes from the OS detection method (getOS) but testing my demo pages that are using the same script I'm not able to reproduce it.

Did you replace all the scripts inside the jquery.mb.YTPlayer.js?
The best would be to test your page without the script minification. Is it possible?

**Comment by kinsbrunner** [comment]
Matteo,
I am attaching the files and code I am using.
Regards.
Alejandro.

The main JS file is using it on the following 

way:
```
    /* ================================
     ===   JQUERY.MB.YTPLAYER   =====
     ================================= */
    (function () {
        // JQUERY.MB.YTPLAYER
        var $ytPlayer = $(".yt-player");
        var $ytPlay = $('#yt-play');
        var $ytVolume = $('#yt-volume');

        $ytPlayer.mb_YTPlayer();
        // YT controls
        $ytPlay.on("click", function (event) {
            event.preventDefault();
            if ($(this).hasClass("fa-play")) {
                $ytPlayer.playYTP();
            } else {
                $ytPlayer.pauseYTP();
            }
            $(this).toggleClass("fa-play fa-pause");
            return false;
        });
        $ytVolume.on("click", function (event) {
            event.preventDefault();
            $ytPlayer.toggleVolume();
            $(this).toggleClass("fa-volume-off fa-volume-up");
            return false;
        });
    }());
````

**Comment by pupunzi** [comment]
Nothing wrong with that code.
Try downloading the latest 3.0.20 release and let me know.
https://github.com/pupunzi/jquery.mb.YTPlayer/archive/3.0.20.zip

**Comment by kinsbrunner** [comment]
Matteo,
I have upgraded to 3.0.20 and errors have dissapeared! :)
However there are 2 things that I am still seeing;
a) Black screen instead of video (already live in expinconsulting.com)
b) I am not being able to remove buttons (I switched showControls property to false - I did this on local version). I believe this is part of another issue but just mention it here as this are the 2 remaining adjustments I need :)
Thanks and regards.
Alejandro.

**Comment by pupunzi** [comment]
@kinsbrunner 

A) On mobile you can't have the video playing; if you set a background image as "mobileFallbackImage" that will be used as fallback behave on mobile.

B) The two buttons you have on your page to control the video are not managed by the YTPlayer script but are a custom implementation you did. If you want to remove them on mobile you should add a condition for that on your script as for ex.:

```
if(jQuery.browser.mobile) {
      jQuery(".yt-controls").hide();
}
```
All the best,
Matteo

**Comment by kinsbrunner** [comment]
Matteo,
Thanks for all your support. I thougth there was a way of showing the video as a Youtube video backgraund (instead of setting a bacground image)... did I missunderstand?
Regards.
Alejandro.

**Comment by pupunzi** [comment]
There's no way at the time to display a Youtube video or any other video as background on mobile devices as the would open the video using the native player. Sorry :-)
